
# System aliases
alias ls='ls --color=auto'
alias lll='ls -lAh --group-directories-first --color=auto'
alias pacgrade="sudo pacman -Syu; /home/jm/.local/bin/bar-functions/dwm_update.sh; refbar"
alias rm='rm -I'
alias clndep='sudo pacman -R $(pacman -Qdtq)'
alias clnrep='printf "Cleaning uninstalled packages\n"; sudo paccache -ruk0; printf "Leaving last version of installed packages\n"; sudo paccache -rk1'
alias pacrem='sudo pacman -R $1; clndep'
alias bime='nvim'
alias newsbloat='newsboat'

# Directory aliases
alias FIS2a='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Assets/FIS2'
alias FIS2c='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Classes/FIS2'
alias FIS2w='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Work/FIS2'
alias AEDAa='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Assets/AEDA'
alias AEDAc='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Classes/AEDA'
alias AEDAw='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Work/AEDA'
alias MNUMa='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Assets/MNUM'
alias MNUMc='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Classes/MNUM'
alias MNUMw='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Work/MNUM'
alias LCOMa='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Assets/LCOM'
alias LCOMc='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Classes/LCOM'
alias LCOMw='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Work/LCOM'
alias TCOMa='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Assets/TCOM'
alias TCOMc='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Classes/TCOM'
alias TCOMw='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno1oSemestre/Work/TCOM'
alias BDADa='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/BDAD/Assets'
alias BDADc='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/BDAD/Classes'
alias BDADw='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/BDAD/Work'
alias CALa='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/CAL/Assets'
alias CALc='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/CAL/Classes'
alias CALw='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/CAL/Work'
alias CGRAa='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/CGRA/Assets'
alias CGRAc='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/CGRA/Classes'
alias CGRAw='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/CGRA/Work'
alias LPOOa='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/LPOO/Assets'
alias LPOOc='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/LPOO/Classes'
alias LPOOw='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/LPOO/Work'
alias SOPEa='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/SOPE/Assets'
alias SOPEc='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/SOPE/Classes'
alias SOPEw='cd /home/jm/Documents/OneDrive/FEUP/2ºAno/2oAno2oSemestre/SOPE/Work'

# Git aliases
alias g='git'
alias gst='git status'
alias gad='git add'
alias grm='git rm'
alias gb='git branch'
alias gc='git commit'
alias gr='git remote'
alias gch='git checkout'
alias gps='git push'
alias gpl='git pull'

# Ya mano
alias intelij='idea'
