#! /bin/sh

sxhkd &

# Launch polybar
~/.config/polybar/launch.sh &

# bspc monitor LVDS-1 -d term code web music comms VI VII VIII IX X
bspc monitor LVDS-1 -d term code VI VII VIII IX X
bspc monitor VGA-1 -d web music comms

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^3' state=tiled
bspc rule -a discord desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a qutebrowser desktop='^9' state=tiled
bspc rule -a mpv desktop='^9' state=tiled

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
jspc config presel_feedback_color "$color1"
